# name tag from hub.docker.com
FROM ubuntu:latest

# Supress warnings about missing front-end. As recommended at:
# http://stackoverflow.com/questions/22466255/is-it-possibe-to-answer-dialog-questions-when-installing-under-docker
ARG DEBIAN_FRONTEND=noninteractive

RUN apt update --yes 
RUN apt upgrade --yes

# install miniconda.
RUN apt install wget -y
RUN wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

ENV PATH /opt/conda/bin:$PATH
ENV TINI_VERSION v0.16.1
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini
ENTRYPOINT [ "/usr/bin/tini", "--" ]
# install miniconda ------------------------------------------------------------------------------------------


# intall jupyterlab on base env
RUN conda install jupyterlab

# common tools for NGS analsys; search version of software and download channel on internet or using a test container with preinstalled conda
RUN conda install trimmomatic=0.39 -c bioconda
RUN conda install bwa=0.7.17 -c bioconda
RUN conda install samtools=1.9 -c bioconda
RUN conda install gatk4=4.1.5.0 -c bioconda
RUN conda install vcftools=0.1.16 -c bioconda
RUN conda install plink=1.90b6.12 -c bioconda

# create env, install r, make it avaible on jupyterlab
RUN conda create -n r35 r=3.5.0 &&\
    conda install -c r r-irkernel -n r35 &&\
    conda run -n r35 Rscript -e 'IRkernel::installspec(name="ir3.5.0",displayname="R 3.5.0")'


# Port for jupyterlab
EXPOSE 8888

WORKDIR "/root"
CMD ["/bin/bash"]